TextWidget:

<TextWidget>:
    BoxLayout:
        orientation: 'vertical'
        size: root.size
        canvas.before:
            Rectangle:
                source: "./img/457794-PFCW5A-392.jpg"
                pos: self.pos
                size: self.size



        BoxLayout:
            orientation: 'vertical'

            BoxLayout:
                orientation: 'horizontal'

                BoxLayout:
                    orientation: 'horizontal'

                    BoxLayout:
                        size_hint_x:0.2
                        orientation:'vertical'
                        Label:
                        Label:
                            id: dl_score
                            font_size:20
                            text:''
                            color:1,1,1,1
                            canvas.before:
                                Color:
                                    rgba:0,0,0,0.8
                                Rectangle:
                                    pos: self.pos
                                    size: self.size
                        Label:

                    BoxLayout:
                        orientation: 'horizontal'

                        Image:
                            id: dl_card1
                            size_hint_x: 0.2
                            size_hint_y: 1
                            source:"./img/blank.png"


                        Image:
                            id: dl_card2
                            size_hint_x: 0.2
                            size_hint_y: 1
                            source:"./img/blank.png"

                        Image:
                            id: dl_card3
                            size_hint_x: 0.2
                            size_hint_y: 1
                            source:"./img/blank.png"

                        Image:
                            id: dl_card4
                            size_hint_x: 0.2
                            size_hint_y: 1
                            source:"./img/blank.png"

                        Image:
                            id: dl_card5
                            size_hint_x: 0.2
                            size_hint_y: 1
                            source:"./img/blank.png"

                        Image:
                            id: dl_card6
                            size_hint_x: 0.2
                            size_hint_y: 1
                            source:"./img/blank.png"

                    Image:
                        id: dl_deck
                        size_hint_x: 0.2
                        size_hint_y: 1
                        source:"./img/card_back.png"

        BoxLayout:
            size_hint_y:0.1

        BoxLayout:
            orientation: 'horizontal'
            canvas.before:
                Rectangle:
                    source:'./img/OIP6N1PN9K4.jpg'
                    pos: self.pos
                    size: self.size

            BoxLayout:
                orientation: 'vertical'

                BoxLayout:
                    orientation: 'horizontal'

                    Label:
                        id: label1
                        font_size: 20
                        text: "hand"

                    Label:
                        id:hand_num
                        font_size: 40
                        text: '5000'
                        color:0,1,1,1

                BoxLayout:
                    orientation: 'horizontal'

                    Label:
                        id: label1
                        font_size: 20
                        text: "bet"

                    Label:
                        id:label1
                        text: '{:.0f}'.format(testSlider.value)
                        font_size:40
                        color:0,1,1,1

                Slider:
                    id: testSlider
                    size_hint_x: 0.75
                    min: 1
                    max: 5000
                    value: 20.0

            Label:
                size_hint_x:0.1

            BoxLayout:
                orientation: 'vertical'
                Label:
                    size_hint_y:0.1
                BoxLayout:
                    orientation:'horizontal'
                    Label:
                        size_hint_x:0.1

                    Image:
                        id: wltextLabel
                        source:"./img/scoreblank.png"

                    Label:
                        size_hint_x:0.1

                Label:
                    size_hint_y:0.1

            Label:
                size_hint_x:0.1

            BoxLayout:
                orientation: 'horizontal'

                BoxLayout:
                    orientation:'vertical'

                    Label:

                    Button:
                        id: DealButton
                        font_size: 20
                        on_press: root.deal()
                        canvas.after:
                            Rectangle:
                                source: "./img/deal.png"
                                pos: self.pos
                                size: self.size

                    Label:

                BoxLayout:
                    orientation:'vertical'

                    Label:
                        id: button1
                        font_size: 20
                        # on_press: root.buttonClicked()
                        # canvas.after:
                        #     Rectangle:
                        #         source: "./img/cman20200409203101338.png"
                        #         pos: self.pos
                        #         size: self.size

                    Label:


                    Button:
                        id: HitButton
                        font_size: 20
                        on_press: root.hit()
                        canvas.after:
                            Rectangle:
                                source: "./img/hit.png"
                                pos: self.pos
                                size: self.size

                BoxLayout:
                    orientation:'vertical'

                    Label:

                    Button:
                        id: StandButton
                        font_size: 20
                        on_press: root.stand()
                        canvas.after:
                            Rectangle:
                                source: "./img/stand.png"
                                pos: self.pos
                                size: self.size

                    Label:

        BoxLayout:
            size_hint_y:0.1

        BoxLayout:
            orientation: 'horizontal'

            BoxLayout:
                size_hint_x:0.2
                orientation:'vertical'
                Label:
                Label:
                    id: pl_score
                    font_size:20
                    text:''
                    color:1,1,1,1
                    canvas.before:
                        Color:
                            rgba:0,0,0,0.8
                        Rectangle:
                            pos: self.pos
                            size: self.size
                Label:


            BoxLayout:
                orientation: 'horizontal'

                Image:
                    id: pl_card1
                    size_hint_y:1
                    source:"./img/blank.png"

                Image:
                    id: pl_card2
                    size_hint_y:1
                    source:"./img/blank.png"

                Image:
                    id: pl_card3
                    size_hint_y:1
                    source:"./img/blank.png"

                Image:
                    id: pl_card4
                    size_hint_y:1
                    source:"./img/blank.png"

                Image:
                    id: pl_card5
                    size_hint_y:1
                    source:"./img/blank.png"

                Image:
                    id: pl_card6
                    size_hint_y:1
                    source:"./img/blank.png"


            BoxLayout:
                size_hint_x:0.2
