TextWidget:

<TextWidget>:
    BoxLayout:
        orientation: 'vertical'
        size: root.size
        canvas.before:
            Rectangle:
                source: "./img/457794-PFCW5A-392.jpg"
                pos: self.pos
                size: self.size



        BoxLayout:
            orientation: 'vertical'

            BoxLayout:
                orientation: 'horizontal'

                BoxLayout:
                    orientation: 'horizontal'

                    Label:
                        size_hint_x: 0.2


                    BoxLayout:
                        orientation: 'horizontal'

                        Label:
                            id: label1
                            size_hint_x: 0.2
                            size_hint_y: 0.7
                            canvas.before:
                                Rectangle:
                                    source:"./img/card_spade_03.png"
                                    pos: self.pos
                                    size: self.size

                        Label:
                            id: label1
                            size_hint_x: 0.2
                            size_hint_y: 0.7
                            canvas.before:
                                Rectangle:
                                    source:"./img/card_spade_03.png"
                                    pos: self.pos
                                    size: self.size

                        Label:
                            id: label1
                            size_hint_x: 0.2
                            size_hint_y: 0.7
                            canvas.before:
                                Rectangle:
                                    source:"./img/card_spade_03.png"
                                    pos: self.pos
                                    size: self.size

                        Label:
                            id: label1
                            size_hint_x: 0.2
                            size_hint_y: 0.7
                            canvas.before:
                                Rectangle:
                                    source:"./img/card_spade_03.png"
                                    pos: self.pos
                                    size: self.size

                        Label:
                            id: label1
                            size_hint_x: 0.2
                            size_hint_y: 0.7
                            canvas.before:
                                Rectangle:
                                    source:"./img/card_spade_03.png"
                                    pos: self.pos
                                    size: self.size

                        Label:
                            id: label1
                            size_hint_x: 0.2
                            size_hint_y: 0.7
                            canvas.before:
                                Rectangle:
                                    source:"./img/card_spade_03.png"
                                    pos: self.pos
                                    size: self.size

                    Label:
                        id: label1
                        font_size: 68
                        size_hint_x: 0.2
                        # text: "dec"
                        canvas.before:
                            Rectangle:
                                source: "./img/OIP.jpg"
                                pos: self.pos
                                size: self.size

        BoxLayout:
            size_hint_y:0.1

        BoxLayout:
            orientation: 'horizontal'
            canvas.before:
                Rectangle:
                    source:'./img/OIP6N1PN9K4.jpg'
                    pos: self.pos
                    size: self.size

            BoxLayout:
                orientation: 'vertical'

                BoxLayout:
                    orientation: 'horizontal'

                    Label:
                        id: label1
                        font_size: 20
                        text: "hand"

                    Label:
                        id:label1
                        font_size: 40
                        text: '50000'
                        color:0,1,1,1

                BoxLayout:
                    orientation: 'horizontal'

                    Label:
                        id: label1
                        font_size: 20
                        text: "bet"

                    Label:
                        id:label1
                        text: '{:.0f}'.format(testSlider.value)
                        font_size:40
                        color:0,1,1,1

                Slider:
                    id: testSlider
                    size_hint_x: 0.75
                    min: 1
                    max: 10000
                    value: 20.0

            Label:
                size_hint_x:0.1

            BoxLayout:
                orientation: 'vertical'
                Label:
                    size_hint_y:0.1
                BoxLayout:
                    orientation:'horizontal'
                    Label:
                        size_hint_x:0.1

                    Label:
                        id: label1
                        font_size: 50
                        text: "YOU WIN"
                        color:1,0,0,1
                        canvas.before:
                            Color:
                                rgba:0,1,1,1
                            Rectangle:
                                pos: self.pos
                                size: self.size
                    Label:
                        size_hint_x:0.1
                        
                Label:
                    size_hint_y:0.1

            Label:
                size_hint_x:0.1

            BoxLayout:
                orientation: 'horizontal'

                BoxLayout:
                    orientation:'vertical'

                    Label:

                    Button:
                        id: button1
                        font_size: 20
                        on_press: root.buttonClicked()
                        canvas.after:
                            Rectangle:
                                source: "./img/cman20200409203101338.png"
                                pos: self.pos
                                size: self.size

                    Label:

                BoxLayout:
                    orientation:'vertical'

                    Button:
                        id: button1
                        font_size: 20
                        on_press: root.buttonClicked()
                        canvas.after:
                            Rectangle:
                                source: "./img/cman20200409203101338.png"
                                pos: self.pos
                                size: self.size

                    Label:


                    Button:
                        id: button1
                        font_size: 20
                        on_press: root.buttonClicked()
                        canvas.after:
                            Rectangle:
                                source: "./img/cman20200409203101338.png"
                                pos: self.pos
                                size: self.size

                BoxLayout:
                    orientation:'vertical'

                    Label:

                    Button:
                        id: button1
                        font_size: 20
                        on_press: root.buttonClicked()
                        canvas.after:
                            Rectangle:
                                source: "./img/cman20200409203101338.png"
                                pos: self.pos
                                size: self.size

                    Label:

        BoxLayout:
            size_hint_y:0.1

        BoxLayout:
            orientation: 'horizontal'

            BoxLayout:
                size_hint_x:0.2
                Label:
                    font_size:20
                    text:'20'

            BoxLayout:
                orientation: 'horizontal'

                Label:
                    id: label1
                    font_size: 30
                    size_hint_y:0.7
                    canvas.before:
                        Rectangle:
                            source:"./img/card_spade_02.png"
                            pos: self.pos
                            size: self.size

                Label:
                    id: label1
                    font_size: 30
                    size_hint_y:0.7
                    canvas.before:
                        Rectangle:
                            source:"./img/card_spade_02.png"
                            pos: self.pos
                            size: self.size

                Label:
                    id: label1
                    size_hint_y: 0.7
                    canvas.before:
                        Rectangle:
                            source:"./img/card_spade_03.png"
                            pos: self.pos
                            size: self.size

                Label:
                    id: label1
                    size_hint_y:0.7
                    canvas.before:
                        Rectangle:
                            source:"./img/card_spade_01.png"
                            pos: self.pos
                            size: self.size

                Label:
                    id: label1
                    size_hint_y:0.7
                    canvas.before:
                        Rectangle:
                            source:"./img/card_spade_01.png"
                            pos: self.pos
                            size: self.size

                Label:
                    id: label1
                    size_hint_y:0.7
                    canvas.before:
                        Rectangle:
                            source:"./img/card_spade_01.png"
                            pos: self.pos
                            size: self.size

            BoxLayout:
                size_hint_x:0.2
